import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const script=path.resolve('scripts/editorial/kotatsu-identity.mjs');
function fixture(){const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'kotatsu-identity-'));const env={...process.env,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1'};const git=args=>spawnSync('git',args,{cwd,env,encoding:'utf8'});assert.equal(git(['init']).status,0);assert.equal(git(['remote','add','origin','https://github.com/withbugs/kotatsu.git']).status,0);fs.mkdirSync(path.join(cwd,'scripts/editorial'),{recursive:true});fs.copyFileSync(script,path.join(cwd,'scripts/editorial/kotatsu-identity.mjs'));fs.cpSync('.githooks',path.join(cwd,'.githooks'),{recursive:true});const cli=(mode,extra={})=>spawnSync(process.execPath,[script,mode],{cwd,env:{...env,...extra},encoding:'utf8'});return{cwd,env,git,cli};}
test('fresh task bootstrap pins local/effective identity despite unrelated inherited global defaults',()=>{
 const f=fixture();try{assert.notEqual(f.cli('check').status,0);assert.equal(f.cli('bootstrap').status,0);assert.equal(f.cli('check').status,0);assert.equal(f.git(['config','--local','user.email']).stdout.trim(),'28248251+withbugs@users.noreply.github.com');for(const extra of [{GIT_AUTHOR_NAME:'Other'},{GIT_COMMITTER_EMAIL:'other@example.invalid'},{GIT_CONFIG_COUNT:'1',GIT_CONFIG_KEY_0:'user.email',GIT_CONFIG_VALUE_0:'other@example.invalid'}])assert.notEqual(f.cli('check',extra).status,0);assert.equal(f.git(['config','--global','--get','user.name']).status,1);}finally{fs.rmSync(f.cwd,{recursive:true,force:true})}
});
test('real commit hooks reject mismatched author and merge identity; outgoing history is checked',()=>{
 const f=fixture();try{assert.equal(f.cli('bootstrap').status,0);const good=f.git(['commit','--allow-empty','-m','good']);assert.equal(good.status,0,good.stderr);assert.equal(f.git(['update-ref','refs/remotes/origin/main','HEAD']).status,0);assert.notEqual(f.git(['commit','--allow-empty','--author=Other <other@example.invalid>','-m','bad']).status,0);assert.equal(f.cli('push').status,0);const bad=f.git(['-c','core.hooksPath=/dev/null','-c','user.name=Other','-c','user.email=other@example.invalid','commit','--allow-empty','-m','fixture bypass']);assert.equal(bad.status,0,bad.stderr);const before=f.git(['rev-parse','HEAD']).stdout;assert.notEqual(f.cli('push').status,0);assert.equal(f.git(['rev-parse','HEAD']).stdout,before);assert.ok(!f.cli('push').stderr.includes('other@example.invalid'));}finally{fs.rmSync(f.cwd,{recursive:true,force:true})}
});
